### ISSUE TITLE
Error invoking action

### ISSUE THREAD

**Issue by johnsturgeon** [kvanh/Keyboard-Maestro-Pushover-Notifications#1]
I'm getting an error running the script

`~/Library/Application Support/Keyboard Maestro/Keyboard Maestro Actions/Pushover Notifications/PushoverNotification.scpt: execution error: Can’t get text 1 thru 14 of "Test title". (-1728) `

When invoking the following action

```
Send a notification via Pushover
Priority: Normal
Title: Notification Title
Notification Message:
HTML formatted notification message. Go here <a href=‘http://test.com'>Here</a>
URL Title:
Test title
URL:
http://google.com
Notification Sound: User Default
Display trimmed results in a window.
```

**Comment by kvanh** [comment]
Well it's many years late, but I did update this in my code. I hope you found one of the clones where people had fixed this.
my latest update adds support for the new custom sounds and file attachments.
